// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvoh6nUlOAJ_PCEaKl_szkb8xk4IcBrQ8',
    appId: '1:859855887043:web:4fbb5cd54966feab99e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    authDomain: 'grocery-app-6ddc9.firebaseapp.com',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
    measurementId: 'G-GYM544EMXE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD02cuYdBy_fYP74ydS7TmWeHG10Mm95sQ',
    appId: '1:859855887043:android:4ef14041092e9ad999e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tlpiNAlnosIRFO7YCVhvEDb_wCAm7X0',
    appId: '1:859855887043:ios:f140451815c2614399e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
    iosClientId:
        '859855887043-ov2t5a6bhllvjq8jugo7sv6m1s3trdv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryUserApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-tlpiNAlnosIRFO7YCVhvEDb_wCAm7X0',
    appId: '1:859855887043:ios:f140451815c2614399e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
    iosClientId:
        '859855887043-ov2t5a6bhllvjq8jugo7sv6m1s3trdv7.apps.googleusercontent.com',
    iosBundleId: 'com.example.groceryUserApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvoh6nUlOAJ_PCEaKl_szkb8xk4IcBrQ8',
    appId: '1:859855887043:web:9ce49bd617602afa99e076',
    messagingSenderId: '859855887043',
    projectId: 'grocery-app-6ddc9',
    authDomain: 'grocery-app-6ddc9.firebaseapp.com',
    storageBucket: 'grocery-app-6ddc9.appspot.com',
    measurementId: 'G-LC5SMH6LR3',
  );
}
